version: "3"
services:
  node-proxy:
    build:
      context: .
      dockerfile: Dockerfile  
    image: gigon/nodejs-proxy:v1.0.0
    volumes:
      - ./proxies:/home/node/app/proxies
    ports:
      - 4000:4000
    command: "node app.js"